@echo off
echo Fixing everything for you...

echo 1. Stopping any broken servers stuck in the background...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8001" ^| find "LISTENING"') do taskkill /f /pid %%a 2>nul

echo 2. Moving into the project folder...
cd /d "%~dp0"

echo 3. Automatically configuring Local IP address for physical Android device testing...
backend\.venv\Scripts\python auto_config_ip.py

echo 4. Installing requirements...
backend\.venv\Scripts\pip install -r backend\requirements.txt

echo 5. Starting the server on all network interfaces...
uvicorn backend.main:app --host 0.0.0.0 --port 8001 --reload
